### ISSUE TITLE
Botão visualizar senha

### ISSUE THREAD

**Issue by Oluccaro** [Oluccaro/web2_lavanderia_online#38]
Fazer os ajustes no botão de mostrar senha. 

Aqui vai uns links úteis:

https://www.geeksforgeeks.org/how-to-toggle-password-visibility-in-forms-using-bootstrap-icons/

https://blog.getbootstrap.com/2021/01/07/bootstrap-icons-1-3-0/

https://icons.getbootstrap.com/icons/eye-fill/

**Comment by lucas-cazionato** [comment]
Botão de visualizar senha ajustado com a classe "bi bi-eye-slash". Sobe no próximo PR.
